# Generated by Django 3.0.7 on 2020-06-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200610_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
