# Generated by Django 3.1 on 2020-08-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20200822_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bendFoward',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
