# Generated by Django 3.1 on 2020-08-23 01:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20200822_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bendFoward',
            field=models.DecimalField(blank=True, decimal_places=1, default=Decimal('0.0'), max_digits=5, null=True),
        ),
    ]
