# Generated by Django 2.2.5 on 2020-08-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20200824_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bendFoward',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
    ]
