# Generated by Django 2.2.5 on 2020-08-24 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20200610_2024'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='MeasurementItem',
        ),
    ]
