# Generated by Django 3.0.6 on 2020-05-18 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pacer', models.IntegerField(blank=True)),
                ('longTimeRun', models.IntegerField(blank=True)),
                ('stepTest', models.IntegerField(blank=True)),
                ('bendFoward', models.DecimalField(blank=True, decimal_places=1, max_digits=5)),
                ('shoulder', models.IntegerField(blank=True)),
                ('upperBody', models.IntegerField(blank=True)),
                ('side', models.IntegerField(blank=True)),
                ('lowerBody', models.IntegerField(blank=True)),
                ('totalFlexibility', models.IntegerField(blank=True)),
                ('pushUp', models.IntegerField(blank=True)),
                ('sitUp', models.IntegerField(blank=True)),
                ('grip', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('sprint', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('longJump', models.DecimalField(blank=True, decimal_places=1, max_digits=5)),
                ('height', models.DecimalField(blank=True, decimal_places=1, max_digits=5)),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=5)),
                ('fat', models.DecimalField(blank=True, decimal_places=1, max_digits=5)),
            ],
        ),
    ]
