# Generated by Django 3.0.6 on 2020-05-18 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_stat_host'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stat',
            old_name='host',
            new_name='name',
        ),
    ]
