# Generated by Django 3.0.6 on 2020-05-18 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stats', '0003_auto_20200518_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='bendFoward',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='stat',
            name='fat',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='stat',
            name='grip',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='stat',
            name='height',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='stat',
            name='longJump',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='stat',
            name='longTimeRun',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stat',
            name='lowerBody',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stat',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stat',
            name='pacer',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='stat',
            name='pushUp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stat',
            name='shoulder',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stat',
            name='side',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stat',
            name='sitUp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stat',
            name='sprint',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='stat',
            name='stepTest',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stat',
            name='totalFlexibility',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stat',
            name='upperBody',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stat',
            name='weight',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
