# Generated by Django 3.0.6 on 2020-05-18 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_auto_20200518_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='bendFoward',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='stat',
            name='fat',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='stat',
            name='grip',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='stat',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='stat',
            name='longJump',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='stat',
            name='lowerBody',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stat',
            name='pacer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stat',
            name='pushUp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stat',
            name='shoulder',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stat',
            name='side',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stat',
            name='sitUp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stat',
            name='sprint',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='stat',
            name='stepTest',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stat',
            name='totalFlexibility',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stat',
            name='upperBody',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stat',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
