# Generated by Django 3.0.6 on 2020-05-18 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_auto_20200518_1336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stat',
            options={'verbose_name_plural': 'Stats'},
        ),
    ]
