# Generated by Django 3.0.6 on 2020-05-20 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stats', '0007_auto_20200520_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stat',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
