# Generated by Django 3.0.6 on 2020-06-01 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stats', '0008_auto_20200520_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stat',
            name='lowerBody',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='school',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='shoulder',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='side',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='upperBody',
        ),
        migrations.AlterField(
            model_name='stat',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL),
        ),
    ]
