# Generated by Django 3.1 on 2020-08-22 01:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stats', '0009_auto_20200601_2208'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stat',
            new_name='Stats',
        ),
    ]
