# Generated by Django 2.2.5 on 2020-08-24 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_stats_name'),
        ('stats', '0010_auto_20200822_1019'),
    ]

    operations = [
    ]
